-- One-time setup: real Snowflake-native isolation for the two demo accounts.
-- Run as ACCOUNTADMIN (or a role with CREATE USER/ROLE). Replace the two
-- passwords before running — Snowflake enforces its default password policy
-- (>=8 chars, upper+lower+digit).

CREATE ROLE IF NOT EXISTS ROLE_DEMO_USER_A;
CREATE ROLE IF NOT EXISTS ROLE_DEMO_USER_B;

CREATE OR REPLACE USER DEMO_USER_A
  PASSWORD = '<REPLACE_ME_A>'
  DEFAULT_ROLE = ROLE_DEMO_USER_A
  DEFAULT_WAREHOUSE = COMPUTE_WH
  MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER DEMO_USER_B
  PASSWORD = '<REPLACE_ME_B>'
  DEFAULT_ROLE = ROLE_DEMO_USER_B
  DEFAULT_WAREHOUSE = COMPUTE_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ROLE_DEMO_USER_A TO USER DEMO_USER_A;
GRANT ROLE ROLE_DEMO_USER_B TO USER DEMO_USER_B;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DEMO_USER_A;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_DEMO_USER_B;

GRANT USAGE ON DATABASE EGLE_VIEW TO ROLE ROLE_DEMO_USER_A;
GRANT USAGE ON DATABASE EGLE_VIEW TO ROLE ROLE_DEMO_USER_B;

CREATE SCHEMA IF NOT EXISTS EGLE_VIEW.DEMO_A;
CREATE SCHEMA IF NOT EXISTS EGLE_VIEW.DEMO_B;

GRANT ALL ON SCHEMA EGLE_VIEW.DEMO_A TO ROLE ROLE_DEMO_USER_A;
GRANT ALL ON FUTURE TABLES IN SCHEMA EGLE_VIEW.DEMO_A TO ROLE ROLE_DEMO_USER_A;
GRANT ALL ON ALL TABLES IN SCHEMA EGLE_VIEW.DEMO_A TO ROLE ROLE_DEMO_USER_A;

GRANT ALL ON SCHEMA EGLE_VIEW.DEMO_B TO ROLE ROLE_DEMO_USER_B;
GRANT ALL ON FUTURE TABLES IN SCHEMA EGLE_VIEW.DEMO_B TO ROLE ROLE_DEMO_USER_B;
GRANT ALL ON ALL TABLES IN SCHEMA EGLE_VIEW.DEMO_B TO ROLE ROLE_DEMO_USER_B;

-- Both roles need to be able to open the Streamlit app itself, granted after
-- the app is created (see deploy.py) with:
--   GRANT USAGE ON STREAMLIT EGLE_VIEW.PUBLIC.DATAMIND TO ROLE ROLE_DEMO_USER_A;
--   GRANT USAGE ON STREAMLIT EGLE_VIEW.PUBLIC.DATAMIND TO ROLE ROLE_DEMO_USER_B;
